# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreateprofile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createprofile(self):
    # Test name: create_profile
    # Step # | name | target | value
    # 1 | open | https://skoolgo.pixelmindit.com:8000/#/ | 
    self.driver.get("https://skoolgo.pixelmindit.com:8000/#/")
    # 2 | setWindowSize | 1366x768 | 
    self.driver.set_window_size(1366, 768)
    # 3 | click | linkText=Sign Up | 
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    # 4 | click | id=fullName | 
    self.driver.find_element(By.ID, "fullName").click()
    # 5 | type | id=fullName | Hanuman
    self.driver.find_element(By.ID, "fullName").send_keys("Hanuman")
    # 6 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 7 | type | id=email | Hanuman@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("Hanuman@gmail.com")
    # 8 | click | id=mobile | 
    self.driver.find_element(By.ID, "mobile").click()
    # 9 | type | id=mobile | 800 486 6733
    self.driver.find_element(By.ID, "mobile").send_keys("800 486 6733")
    # 10 | click | id=personalId | 
    self.driver.find_element(By.ID, "personalId").click()
    # 11 | type | id=personalId | 400345677822
    self.driver.find_element(By.ID, "personalId").send_keys("400345677822")
    # 12 | click | css=.MuiInputBase-input | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiInputBase-input").click()
    # 13 | click | css=.MuiTypography-subtitle1 | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTypography-subtitle1").click()
    # 14 | click | css=.MuiTypography-root:nth-child(94) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTypography-root:nth-child(94)").click()
    # 15 | click | css=.MuiPickersCalendar-week:nth-child(2) > div:nth-child(3) .MuiTypography-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiPickersCalendar-week:nth-child(2) > div:nth-child(3) .MuiTypography-root").click()
    # 16 | click | id=nationality | 
    self.driver.find_element(By.ID, "nationality").click()
    # 17 | select | id=nationality | label=India
    dropdown = self.driver.find_element(By.ID, "nationality")
    dropdown.find_element(By.XPATH, "//option[. = 'India']").click()
    # 18 | click | id=gender | 
    self.driver.find_element(By.ID, "gender").click()
    # 19 | select | id=gender | label=Male
    dropdown = self.driver.find_element(By.ID, "gender")
    dropdown.find_element(By.XPATH, "//option[. = 'Male']").click()
    # 20 | click | css=.col-xl-7 | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-xl-7").click()
    # 21 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 22 | type | id=password | 123456
    self.driver.find_element(By.ID, "password").send_keys("123456")
    # 23 | click | id=confirmPassword | 
    self.driver.find_element(By.ID, "confirmPassword").click()
    # 24 | type | id=confirmPassword | 123456
    self.driver.find_element(By.ID, "confirmPassword").send_keys("123456")
    # 25 | click | css=.custom-control-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".custom-control-label").click()
    # 26 | click | id=create-account | 
    self.driver.find_element(By.ID, "create-account").click()
    # 27 | click | css=.form-control:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").click()
    # 28 | type | css=.form-control:nth-child(1) | 1
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").send_keys("1")
    # 29 | type | css=.form-control:nth-child(2) | 2
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").send_keys("2")
    # 30 | type | css=.form-control:nth-child(3) | 3
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(3)").send_keys("3")
    # 31 | type | css=.form-control:nth-child(4) | 4
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(4)").send_keys("4")
    # 32 | click | css=.btn-block | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-block").click()
    # 33 | mouseOver | css=.btn-block | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-block")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 34 | mouseOut | css=.btn-block | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
